name: analyze app
on: workflow_dispatch
jobs:
  analyze:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:latest
    steps:
    - uses: actions/checkout@v3
    - run: set -e
    - run: export BOT="false"
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter pub run custom_lint
    