name: analyze app
on: workflow_dispatch
jobs:
  analyze:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable
    steps:
    - uses: actions/checkout@v3
    - run: flutter pub get
    - run: flutter analyze
    #- run: flutter pub run custom_lint